---
name: Checks

on: [push, pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run mdl
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: '**/*.md'
          # If we need to add a future configuration
          # config: mdl.yaml

  markdown-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
