---
name: Checks

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run mdl
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: '**/*.md'
          config: mdl.yml

  markdown-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
